apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: search-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - image: index.docker.io/banomaster/rso-backend-movies-search:latest
        name: search
        imagePullPolicy: Always
        env:
          - name: ETCD_URL
            value: http://etcd:2379
          - name: ENV
            value: dev
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
      imagePullSecrets:
      - name: myregistrykey